### ISSUE TITLE
Working example?

### ISSUE THREAD

**Issue by ghost** [Sauermann/modern-psopt-interface#1]
If there would, I'd like to see a working example using this interface.
(Or simply, I can't figure out how to use this interface.)

In fact, I can't even make libModernPsoptInterface.a, because of (well, I think I'm again doing something silly):

g++ -c -O0 -g -std=c++0x -DLAPACK -DUNIX -DSPARSE_MATRIX -DUSE_IPOPT -fomit-frame-pointer -pipe -DNDEBUG -pedantic-error
s -Wall -DHAVE_MALLOC -std=c++0x -pedantic -IC:/PSOPT/.target/include ModernPsoptInterface.cxx -o ModernPsoptInterface.o

In file included from C:/PSOPT/.target/include/dmatrixv.h:1840:0,
                 from ModernPsoptInterface.h:25,
                 from ModernPsoptInterface.cxx:23:
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++/bits/stl_vector.h: In member function 'std::vector<_Tp, _Allo
c>::size_type std::vector<_Tp, _Alloc>::_M_check_len(std::vector<_Tp, _Alloc>::size_type, const char_) const':
C:/PSOPT/.target/include/f2c.h:160:18: error: expected unqualified-id before '(' token
 #define max(a,b) ((a) >= (b) ? (a) : (b))
                  ^
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++/bits/stl_bvector.h: In member function 'std::vector<bool, _Al
loc>::size_type std::vector<bool, _Alloc>::_M_check_len(std::vector<bool, _Alloc>::size_type, const char_) const':
C:/PSOPT/.target/include/f2c.h:160:18: error: expected unqualified-id before '(' token
 #define max(a,b) ((a) >= (b) ? (a) : (b))
                  ^
......

**Comment by Sauermann** [comment]
Sorry, but I do not have a working example ... At the time I started this extension, I thought it would be an interesting idea, but never had the time to finish this piece of software (this also explains the lack of documentation).
Currently I try to maintain the psopt-installer because I believe it helps people to use PSOPT, but since I have not used PSOPT myself for more than a year, I don't feel like puting work into this modern-psopt-interface.

**Comment by ghost** [comment]
I understand. Thanks for your help.
